apiVersion: apps/v1
kind: Deployment
metadata:
  name: forge-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forge
  template:
    metadata:
      labels:
        app: forge
    spec:
      hostPID: true
      containers:
        - name: forge-container
          image: vsramchaik/aether-forge:latest
          securityContext:
            privileged: true
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          env:
            - name: WORKER_TYPE
              value: Build
            - name: AWS_BUCKET_NAME
              value: aether-bucket
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_SQS_URL
              value: https://sqs.us-east-1.amazonaws.com/502413910473/aether-queue
            # - name: AWS_ACCESS_KEY_ID
            #   value: ""
            # - name: AWS_SECRET_ACCESS_KEY
            #   value: ""
            # - name: AWS_SESSION_TOKEN
            #   value: ""

---
apiVersion: v1
kind: Service
metadata:
  name: forge-service
spec:
  selector:
    app: forge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
