apiVersion: apps/v1
kind: Deployment
metadata:
  name: forge-deployment
  namespace: aether
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forge
  template:
    metadata:
      labels:
        app: forge
    spec:
      nodeSelector:
        node-group: forge
      hostPID: true
      containers:
        - name: forge-container
          image: vsramchaik/aether-forge:latest
          securityContext:
            privileged: true
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "750m"
              memory: "512Mi"
            limits:
              cpu: "1200m"
              memory: "1Gi"
          env:
            - name: APP_ENV
              value: prod
            - name: WORKER_TYPE
              value: Build
            - name: AWS_BUCKET_NAME
              value: aether-bucket
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_SQS_URL
              value: https://sqs.us-east-1.amazonaws.com/502413910473/aether-queue
            - name: GRPC_SERVER_ADDRESS
              value: "launchpad-service:50051"
            - name: LOGS_GRPC_SERVER_ADDRESS
              value: "logify-service:50051"
            # - name: AWS_ACCESS_KEY_ID
            #   valueFrom:
            #     secretKeyRef:
            #       name: aws-credentials
            #       key: AWS_ACCESS_KEY_ID
            # - name: AWS_SECRET_ACCESS_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: aws-credentials
            #       key: AWS_SECRET_ACCESS_KEY
            # - name: AWS_SESSION_TOKEN
            #   valueFrom:
            #     secretKeyRef:
            #       name: aws-credentials
            #       key: AWS_SESSION_TOKEN

---
apiVersion: v1
kind: Service
metadata:
  name: forge-service
  namespace: aether
spec:
  selector:
    app: forge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
