apiVersion: apps/v1
kind: Deployment
metadata:
  name: forge-deployment
  namespace: aether
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forge
  template:
    metadata:
      labels:
        app: forge
    spec:
      nodeSelector:
        node-group: forge
      hostPID: true
      containers:
        - name: forge-container
          image: vsramchaik/aether-forge:latest
          securityContext:
            privileged: true
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "550m"
              memory: "512Mi"
            limits:
              cpu: "700m"
              memory: "1Gi"
          env:
            - name: APP_ENV
              value: prod
            - name: WORKER_TYPE
              value: Build
            - name: AWS_BUCKET_NAME
              value: aether-bucket
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_SQS_URL
              value: https://sqs.us-east-1.amazonaws.com/502413910473/aether-queue
            - name: GRPC_SERVER_ADDRESS
              value: "launchpad-service:50051"
            - name: LOGS_GRPC_SERVER_ADDRESS
              value: "logify-service:50051"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SESSION_TOKEN

---
apiVersion: v1
kind: Service
metadata:
  name: forge-service
  namespace: aether
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
spec:
  selector:
    app: forge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: forge-scaled-object
  namespace: aether
spec:
  scaleTargetRef:
    name: forge-deployment
  triggers:
    - type: aws-sqs-queue
      metadata:
        queueName: "aether"
        queueLength: "10"
        awsRegion: "us-east-1"
        awsAccountID: "502413910473"
  minReplicaCount: 1
  maxReplicaCount: 2
