apiVersion: apps/v1
kind: Deployment
metadata:
  name: launchpad-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: launchpad-app
  template:
    metadata:
      labels:
        app: launchpad-app
    spec:
      initContainers:
        - name: migrate-db
          image: vsramchaik/aether-launchpad:latest
          env:
            - name: DATABASE_URL
              value: "postgresql://vaibhavadmin:vaibhavadmin@main-db.ctnalk0fsjpr.us-east-1.rds.amazonaws.com:5432/aether?sslmode=disable"
          command:
            - "sh"
            - "-c"
            - |
              pnpm run migrate
              echo "Drizzle migrations applied successfully."
        - name: fetch-proxy-ip
          image: bitnami/kubectl:latest
          command:
            - "sh"
            - "-c"
            - |
              PROXY_IP=$(kubectl get svc proxy-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
              while [ -z "$PROXY_IP" ]; do
                sleep 5
                PROXY_IP=$(kubectl get svc proxy-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
              done
              kubectl create configmap proxy-ip-config --from-literal=PROXY_IP=$PROXY_IP -o yaml --dry-run=client | kubectl apply -f -
      containers:
        - name: launchpad-app-container
          image: vsramchaik/aether-launchpad:latest
          ports:
            - containerPort: 8000 # HTTP server
            - containerPort: 50051 # gRPC
          resources:
            requests:
              memory: 500Mi
              cpu: 250m
            limits:
              memory: 750Mi
              cpu: 500m
          env:
            - name: DATABASE_URL
              value: "postgresql://vaibhavadmin:vaibhavadmin@main-db.ctnalk0fsjpr.us-east-1.rds.amazonaws.com:5432/aether?sslmode=disable"
            - name: GRPC_SERVER_ADDRESS
              value: "0.0.0.0:50051"
            - name: PROXY_SVC
              valueFrom:
                configMapKeyRef:
                  name: proxy-ip-config
                  key: PROXY_IP

---
apiVersion: v1
kind: Service
metadata:
  name: launchpad-service
spec:
  selector:
    app: launchpad-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-ip-config
data:
  PROXY_IP: ""
