apiVersion: apps/v1
kind: Deployment
metadata:
  name: launchpad-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: launchpad-app
  template:
    metadata:
      labels:
        app: launchpad-app
    spec:
      containers:
        - name: launchpad-app-container
          image: vsramchaik/aether-launchpad:latest
          ports:
            - containerPort: 8000 # HTTP server
            - containerPort: 50051 # gRPC
          resources:
            requests:
              memory: 500Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 500m
          env:
            - name: DATABASE_URL
              value: "postgresql://vaibhav:vaibhav@postgres:5432/aether"
            - name: GRPC_SERVER_ADDRESS
              value: "0.0.0.0:50051"
      initContainers:
        - name: migrate
          image: vsramchaik/aether-launchpad:latest
          env:
            - name: DATABASE_URL
              value: "postgresql://vaibhav:vaibhav@postgres:5432/aether"
          command:
            - "sh"
            - "-c"
            - |
              apt-get update && apt-get install -y netcat-openbsd

              cp /scripts/run-migrations.sh /app/
              chmod +x /app/run-migrations.sh

              cd /app && ./run-migrations.sh
          volumeMounts:
            - name: drizzle-scripts
              mountPath: /scripts
      volumes:
        - name: drizzle-scripts
          configMap:
            name: drizzle-scripts
---
apiVersion: v1
kind: Service
metadata:
  name: launchpad-service
spec:
  selector:
    app: launchpad-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP
