---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: launchpad-sa
  namespace: aether
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-reader
  namespace: aether
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-services
  namespace: aether
subjects:
  - kind: ServiceAccount
    name: launchpad-sa
roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-ip-config
  namespace: aether
data:
  PROXY_IP: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: launchpad-deployment
  namespace: aether
spec:
  replicas: 1
  selector:
    matchLabels:
      app: launchpad-app
  template:
    metadata:
      labels:
        app: launchpad-app
    spec:
      nodeSelector:
        node-group: general
      serviceAccountName: launchpad-sa
      initContainers:
        - name: migrate-db
          image: vsramchaik/aether-launchpad:latest
          env:
            - name: DATABASE_URL
              value: "postgresql://vaibhavadmin:vaibhavadmin@main-db.ctnalk0fsjpr.us-east-1.rds.amazonaws.com:5432/aether?sslmode=disable"
          command:
            - "sh"
            - "-c"
            - |
              pnpm run migrate
              echo "Drizzle migrations applied successfully."
        - name: fetch-proxy-ip
          image: bitnami/kubectl:latest
          command:
            - "sh"
            - "-c"
            - |
              echo "Starting fetch-proxy-ip init container"
              PROXY_IP=$(kubectl get svc proxy-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
              echo "Initial PROXY_IP value: $PROXY_IP"

              ATTEMPT=1
              while [ -z "$PROXY_IP" ]; do
                echo "Attempt $ATTEMPT: PROXY_IP is empty, waiting 5 seconds before retry"
                sleep 5
                PROXY_IP=$(kubectl get svc proxy-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
                echo "Attempt $ATTEMPT: New PROXY_IP value: $PROXY_IP"
                ATTEMPT=$((ATTEMPT+1))
              done

              echo "PROXY_IP found: $PROXY_IP"
              echo "Creating/updating ConfigMap proxy-ip-config"
              kubectl create configmap proxy-ip-config --from-literal=PROXY_IP=$PROXY_IP -o yaml --dry-run=client | kubectl apply -f -

              echo "ConfigMap creation/update command executed"
              echo "Verifying ConfigMap content:"
              kubectl get configmap proxy-ip-config -o yaml

              echo "fetch-proxy-ip init container completed"
      containers:
        - name: launchpad-app-container
          image: vsramchaik/aether-launchpad:latest
          ports:
            - containerPort: 8000 # HTTP server
            - containerPort: 50051 # gRPC
          resources:
            requests:
              memory: 500Mi
              cpu: 250m
            limits:
              memory: 750Mi
              cpu: 500m
          env:
            - name: DATABASE_URL
              value: "postgresql://vaibhavadmin:vaibhavadmin@main-db.ctnalk0fsjpr.us-east-1.rds.amazonaws.com:5432/aether?sslmode=disable"
            - name: GRPC_SERVER_ADDRESS
              value: "0.0.0.0:50051"
            - name: PROXY_SVC
              valueFrom:
                configMapKeyRef:
                  name: proxy-ip-config
                  key: PROXY_IP
            # - name: AWS_ACCESS_KEY_ID
            #   valueFrom:
            #     secretKeyRef:
            #       name: aws-credentials
            #       key: AWS_ACCESS_KEY_ID
            # - name: AWS_SECRET_ACCESS_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: aws-credentials
            #       key: AWS_SECRET_ACCESS_KEY
            # - name: AWS_SESSION_TOKEN
            #   valueFrom:
            #     secretKeyRef:
            #       name: aws-credentials
            #       key: AWS_SESSION_TOKEN

---
apiVersion: v1
kind: Service
metadata:
  name: launchpad-service
  namespace: aether
spec:
  selector:
    app: launchpad-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP
