apiVersion: apps/v1
kind: Deployment
metadata:
  name: logify-deployment
  namespace: aether
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logify
  template:
    metadata:
      labels:
        app: logify
    spec:
      nodeSelector:
        node-group: forge
      containers:
        - name: logify-container
          image: vsramchaik/aether-logify:latest
          ports:
            - containerPort: 8000 # HTTP server
            - containerPort: 50051 # gRPC
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          env:
            - name: PORT
              value: "8080"
            - name: APP_ENV
              value: prod
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_KINESIS_STREAM
              value: aether-logs-stream
            - name: AWS_KINESIS_STREAM_PARTITION_KEY
              value: aether-build-logs
            - name: GRPC_SERVER_ADDRESS
              value: "0.0.0.0:50051"
            - name: MAIN_DB_DATABASE
              value: aether
            - name: DB_DATABASE
              value: aether-logs
            - name: DB_USERNAME
              value: vaibhavadmin
            - name: DB_PASSWORD
              value: vaibhavadmin
            - name: DB_PORT
              value: "5432"
            - name: DB_HOST
              value: main-db.ctnalk0fsjpr.us-east-1.rds.amazonaws.com
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SESSION_TOKEN

---
apiVersion: v1
kind: Service
metadata:
  name: logify-service
  namespace: aether
spec:
  selector:
    app: logify
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP
