apiVersion: apps/v1
kind: Deployment
metadata:
  name: logify-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logify
  template:
    metadata:
      labels:
        app: logify
    spec:
      containers:
        - name: logify-container
          image: vsramchaik/aether-logify:latest
          ports:
            - containerPort: 8000 # HTTP server
            - containerPort: 50051 # gRPC
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          env:
            - name: PORT
              value: "8080"
            - name: APP_ENV
              value: local
            - name: GRPC_SERVER_ADDRESS
              value: "0.0.0.0:50051"
---
apiVersion: v1
kind: Service
metadata:
  name: logify-service
spec:
  selector:
    app: logify
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
  type: LoadBalancer
