apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
  namespace: aether
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      nodeSelector:
        node-group: forge
      containers:
        - name: proxy-container
          image: vsramchaik/aether-proxy:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "250Mi"
            limits:
              cpu: "300m"
              memory: "300Mi"
          env:
            - name: BUCKET_BASE_PATH
              value: https://aether-bucket.s3.amazonaws.com/projects
            - name: PORT
              value: "9000"
            - name: APP_ENV
              value: prod
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SESSION_TOKEN

---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: aether
spec:
  selector:
    app: proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: LoadBalancer
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: proxy-scaledobject
  namespace: aether
spec:
  scaleTargetRef:
    name: proxy-deployment
  pollingInterval: 15 # Check each trigger every 15 seconds
  cooldownPeriod: 300 # Wait 5 minutes before scaling down
  minReplicaCount: 1 # Minimum number of replicas
  maxReplicaCount: 2 # Maximum number of replicas
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "50"
