service: forge-service

provider:
  name: aws
  runtime: nodejs20.x
  role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/${env:AWS_ROLE_NAME}
  environment:
    AWS_ACCOUNT_ID: ${env:AWS_ACCOUNT_ID}
    ROLE_NAME: ${env:AWS_ROLE_NAME}
    BUCKET_NAME: ${env:S3_PROJECT_BUCKET}
    QUEUE_NAME: ${env:BUILD_PROJECTS_QUEUE}

plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild

functions:
  buildProject:
    handler: src/handler.buildProject
    events:
      - sqs:
          arn: arn:aws:sqs:${self:provider.region}:${env:AWS_ACCOUNT_ID}:${self:custom.queueName}
          batchSize: 1
    environment:
      DEPLOY_TO_S3_FUNCTION_NAME: ${self:service}-${sls:stage}-deployToS3
      S3_BUCKET_NAME: ${env:S3_PROJECT_BUCKET}
    timeout: 900 # 15 minutes

custom:
  esbuild:
    bundle: true
    minify: false
  queueName: ${env:BUILD_PROJECTS_QUEUE}
# If creating the queue as part of this stack:
# resources:
#   Resources:
#     MySqsQueue:
#       Type: AWS::SQS::Queue
#       Properties:
#         QueueName: ${self:custom.queueName}
