service: kinesis-consumer-lambda

provider:
  name: aws
  runtime: provided.al2023
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  role: arn:aws:iam::502413910473:role/LabRole
  environment:
    BUCKET_NAME: aether-logs-bucket
    KINESIS_STREAM_NAME: aether-logs-stream

package:
  patterns:
    - "!./**"
    - "./bootstrap"

functions:
  consumer:
    handler: bootstrap
    events:
      - stream:
          type: kinesis
          arn:
            Fn::Join:
              - ":"
              - - arn
                - aws
                - kinesis
                - Ref: AWS::Region
                - Ref: AWS::AccountId
                - stream/${self:provider.environment.KINESIS_STREAM_NAME}
