service: kinesis-consumer-lambda

provider:
  name: aws
  runtime: provided.al2023
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  role: arn:aws:iam::502413910473:role/LabRole
  environment:
    DATABASE_URL: postgresql://vaibhavadmin:vaibhavadmin@main-db.ctnalk0fsjpr.us-east-1.rds.amazonaws.com:5432/aether-logs?sslmode=disable
    KINESIS_STREAM: aether-logs-stream
  vpc:
    securityGroupIds:
      - sg-06324f4e6f4bddb80
    subnetIds:
      - subnet-08d5f096147effbd3
      - subnet-057cf9a9cd6e310ec

package:
  patterns:
    - "!./**"
    - "./bootstrap"

functions:
  consumer:
    handler: bootstrap
    events:
      - stream:
          type: kinesis
          arn:
            Fn::Join:
              - ":"
              - - arn
                - aws
                - kinesis
                - Ref: AWS::Region
                - Ref: AWS::AccountId
                - stream/${self:provider.environment.KINESIS_STREAM}
