service: s3proxy

provider:
  name: aws
  runtime: provided.al2023
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  role: arn:aws:iam::502413910473:role/LabRole
  environment:
    BUCKET_NAME: aether-bucket

package:
  patterns:
    - "!./**"
    - "./bootstrap"

functions:
  proxy:
    handler: bootstrap
    events:
      - http:
          path: /{projectId}/{proxy+}
          method: ANY
      - http:
          path: /{projectId}
          method: ANY
    environment:
      BUCKET_NAME: aether-bucket
